### PR TITLE
Fix goBack

### PR DESCRIPTION
**Pull request by robxyy**

### CODE REVIEW

**Comment by kelset** [comment]
What is this PR accomplishing? Can you provide a test case? Is it solving some open issues?

**Comment by robxyy** [comment]
Fix #1213 
AScreen(a-key)->BScreen(b-key)->CScreen(c-key)->AScreen
navigation.goBack(akey)

**Comment by rpopovici** [comment]
@robxyy how are you accessing previous state keys from inside the route, because navigation.state is not exposing any previous routes information?

**Comment by robxyy** [comment]
@rpopovici Save the navigation.state.key and send it to the next screen, and then get the previous status key from navigation.state.params until we want it.

**Comment by rpopovici** [comment]
@robxyy I know that, but it's not convenient. Beside this, goBackFrom was introduced to make goBack idempotent when you press the back button multiple times. You removed that feature now and have nothing to replace it. I believe that goBackTo should be an alternative action not a replacement for goBackFrom

**Comment by robxyy** [comment]
@rpopovici Well, you are right, and I also agree that goBackTo is great. Since goBack is blurry, so I removed this feature and replaced it.

**Pull request closed without merging**
