### PR TITLE
Dynamic Modals 

### PR DESCRIPTION
**Pull request by jeffreymendez1993**
* added the capability to adjust the mode per screen route through screenProps and a top level-navigator.

### CODE REVIEW

**Comment by ericvicenti** [comment]
Hmm, doesn't this cause broken-looking animations? Could you re-open once you've done the following?

- Test thoroughly and describe how you tested it
- Add an example to the playground app that utilizes this new option
- Take screenshots/videos of the behavior on both platforms
- Write documentation

**Comment by jeffreymendez1993** [comment]
@ericvicenti  It does not. It works perfectly fine for me on iOS and android. Sure i'll do it this weekend when I get spare time.

**Comment by jameskhamil** [comment]
@jeffreymendez1993, I know that is a daunting list of requirements from @ericvicenti, but are you still interested in doing it?

**Comment by herkyl** [comment]
@jeffreymendez1993 could you write a small example on how to use it, I would love to test it out

**Comment by JulianKingman** [comment]
Would it make more sense to make `mode` a navigationOptions property?

**Comment by jeffreymendez1993** [comment]
Will try to get to this this weekend sorry about that! and yes @jameskhamil

**Comment by jeffreymendez1993** [comment]
Actually it kinda brings you down a bad rabbit hole if you have gestures enabled and you are trying to pop a scene but the current scene is a modal type. Say you navigate to a Modal -> NormalScene -> popBack to the Modal -> now try to pop a scene as a gesture. You actually have to manually track mode and it gets annoying. This should be added to the navigationConfig as an option.

**Comment by acomito** [comment]
I need this! Excited for the PR.

**Comment by JulianKingman** [comment]
@jeffreymendez1993 if mode were allowed in navigationOptions, you could pass it to _getTransitionConfig here: https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/views/CardStack/CardStack.js#L429
I think you can get the options from _getScreenDetails (here: https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/views/CardStack/CardStack.js#L145)

Otherwise, maybe you could keep it in the state somehow?

**Comment by slicejunk** [comment]
for people coming from ex-navigation, 
a list of all the features that do no work any more would save a lot of time.

**Comment by JulianKingman** [comment]
I started a separate PR

**Pull request closed without merging**
