### PR TITLE
Navigator which is not front is reacting to action by back processing…

### PR DESCRIPTION
**Pull request by nisin**
… when using multiple navigators.

If you multiplex this with "Stack -> Stack" and you tap the "Back" button on the navigation bar, I want you to operate only on the front Stack which is displaying the navigation bar originally , It solves the problem that "Back" is executed for all Stacks.

```
Stack 0
    TopScene
    Stack 1
       Page 0
       Page 1 <- This is displayed
```

If you create a navigation in the above state and tap the displayed Back button, you can check the difference in behavior.

### CODE REVIEW

**Comment by nisin** [comment]
I found it a problem in operation and withdraw it

**Comment by nisin** [comment]
fix problem. reopen this PR.

**Comment by nihgwu** [comment]
I think this is the wrong way, what if I have a nested navigators like 
```
StackNavigator
  StackNavigaotr
    StackNavigator
```
Although it's unlikely to happen in a real case, but tackling nested navigators in `react-navigation` is always tricky.

**Comment by ericvicenti** [comment]
Can you describe in more detail what the bug is, including some example code that others can use to reproduce it?

**Pull request closed without merging**
