### PR TITLE
Update top-level component nav documentation

### PR DESCRIPTION
**Pull request by taranda**
The code example listed in the current documentation results in a deprecation warning.  This update should work without a deprecation warning.

When I tried the current code example, I received a warning that the navigation action type has changed to "Navigation/NAVIGATE" and that the old type is being deprecated.

This change to the code example in the documentation works with the latest react-navigation version and makes use of the NavigationActions class.

### CODE REVIEW

**Comment by taranda** [comment]
I am not sure why tests are failing. All this PR does is change one mark down file in the docs.   The failed tests are in other files  in the code base. Does the current master branch pass all of its tests?

**Comment by matthamil** [comment]
@taranda looks like it's failing on Prettier checks, no actual tests are failing.

**Comment by taranda** [comment]
Makes sense...and the master branch shows a CircleCI failure as well.   I'll rebase.

**Comment by spencercarli** [comment]
Failing tests [were my fault](https://media.giphy.com/media/xUA7bbo8QK36rb4R44/giphy.gif). They're fixed now and as soon as circle finishes I'll merge this. Thanks @taranda!

**Comment by taranda** [comment]
Thanks!

**Pull request merged**
