### PR TITLE
Fix header title style not applied to custom title component

### PR DESCRIPTION
**Pull request by cychiuae**
Consider this small example:

```js
const MyHomeScreen = ({ navigation }) => (
  <MyNavScreen
    banner="Home Screen"
    navigation={navigation}
  />
);
MyHomeScreen.navigationOptions = {
  header: () => ({
    title: (
      <SampleText>
        Welcome
      </SampleText>
    ),
    titleStyle: {
      backgroundColor: 'red',
    },
  }),
};
```

Before the fix:
screen shot 2017-03-11 at 12 53 51 pm

After the fix:
screen shot 2017-03-11 at 12 54 06 pm

### CODE REVIEW

**Comment by ericvicenti** [comment]
This will cause the same style to be added to the View and the Text components. Can we take a different approach and add a new option that configures only the header `titleViewStyle`?

**Comment by satya164** [comment]
Why not pass style to your custom view directly instead of adding a configuration option?

**Comment by cychiuae** [comment]
@satya164 

> Why not pass style to your custom view directly instead of adding a configuration option?

That's because I want to remove the left and right margin actually instead of changing the background color of that view.

Do you have a better solution for that?

**Comment by satya164** [comment]
You could use negative margins. Though in this case you are essentially replacing the header. Which is @grabbou working on

**Comment by grabbou** [comment]
I am going to close this pull request in favour of the one that allows using custom header component. Thank you @cychiuae for suggesting these changes, but we decided to take the direction as mentioned by @satya164. Looking forward to your next PR!

**Pull request closed without merging**
