### PR TITLE
Adding search to docs website

### PR DESCRIPTION
**Pull request by malashkevich**
With this PR I add search functionality to docs website as per request #2519 and #1252.
Search was implemented using [Algolia](https://community.algolia.com/docsearch/). Actually search was configured buy Algolia team. All I had to implement - integrate it into website.

### CODE REVIEW

**Comment by rmevans9** [comment]
@malashkevich would it be possible to post a few screenshots of what this looks like so we can see it without pulling your branch and building the entire thing?

**Comment by malashkevich** [comment]
Hi @rmevans9.
Sure here are some screenshots:


I changed several colors in search result but leave whole look the same as original.

**Comment by rmevans9** [comment]
Looks great!

**Comment by malashkevich** [comment]
Thanks @rmevans9. Hope it will be approved soon.

**Comment by matthamil** [comment]
@malashkevich looks like you have a small conflict in `website/src/AppFrame.js`.

**Comment by matthamil** [comment]
cc: @spencercarli anything you want changed in this? LGTM. My only concern would be that it appears the search bar is hidden on mobile, but for an initial search functionality this looks good.

**Comment by spencercarli** [comment]
This looks good to me! We can merge once those eslint/prettier errors are taken care of. You can run `npm run test` to see them in dev.

**Comment by malashkevich** [comment]
Thanks @spencercarli. I was able to fix them.
We can also think about search in mobile mode next.

**Comment by spencercarli** [comment]
Wonderful! Thank you 😄

Yeah, mobile search can be looked into later on, not a priority

**Comment by brentvatne** [comment]
hey @malashkevich! do you have access to the algolia account tied to this still? if so, can you add me to the "team" for it?

**Comment by malashkevich** [comment]
Hi @brentvatne.
Actually, I used https://community.algolia.com/docsearch/.
There is no special account. But If you want - I can ask guys from algolia to move docSearch to your account. I also may ask docSearch maintainers to update indexes for the new site.

**Pull request merged**
