### PR TITLE
fixed bug with wrong label&icon in Drawer

### PR DESCRIPTION
**Pull request by nico1510**
This is supposed to fix https://github.com/react-community/react-navigation/issues/1266. 

The problem is that when nesting a StackNavigator with multiple screens inside a DrawerNavigator, then the screen options of the nested (StackNavigator) screens appear in the Drawer. It is of course possible that this is intended behaviour but me and the person who opened the issue think this should not be the default. 
With this fix, the screen options of the root (first) scene are used for displaying the label & icon in the Drawer no matter which route is currently active in the child StackNavigator.

### CODE REVIEW

**Comment by skevy** [comment]
@nico1510 could you do me a quick favor and add a comment near your change explaining what it's doing? I'm sure this code is going to be refactored at some point, and I don't want to regress this fix.

**Comment by skevy** [comment]
Also, you have a linting error. Please run your file through `eslint --fix` so that it's Prettiered. :)

**Comment by nico1510** [comment]
Hi @skevy I updated this PR to include a fix to a related problem. 
The scenario is still the same. If you have a DrawerNavigator where one of its screens is a StackNavigator with multiple screens, I wanted to achieve the following: 

Regardless of which screen is currently active in the StackNavigator ...

1. ... always display the screen options of the first screen (of the StackNavigator). This is what you have already reviewed :white_check_mark: 
2. ... always navigate to the first screen (of the StackNavigator) if the corresponding item in the Drawer is pressed. That way pressing an item in the Drawer always navigates to the same screen as everything else would be rather unexpected behaviour in my opinion. -> You have to review this

I also added comments for both changes, fixed the formatting and resolved a merge conflict.

**Comment by vonovak** [comment]
this PR has an unwanted side effect - 
> always navigate to the first screen (of the StackNavigator) if the corresponding item in the Drawer is pressed. 

```
const AStack = StackNavigator({
  AOne: { screen: ... },
  ATwo: { screen: ... },
});

const BStack = StackNavigator({
  BOne: { screen: ...  },
  BTwo: { screen: ... },
});

export default DrawerNavigator({
  AStack: { screen: AStack },
  BStack: { screen: BStack },
});
```

1 . `AOne` is shown
2 . go to `ATwo` from `AOne`
3 . open drawer and go to `BStack` (ie. `BOne`)
4 . open drawer and go to `AStack` (ie. `AOne`)
 -> now the `AStack` has: `AOne`, `ATwo`, `AOne` in it...

**Comment by nico1510** [comment]
I agree and I noticed that when I wrote the fix but I did not find any way of making it work with reset. I tried the following in DrawerSidebar.js:

```javascript
       subAction = NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({
              routeName: route.routes[0].routeName,
            })
          ]
        });
      }
      this.props.navigation.navigate(route.routeName, undefined, subAction);
```
Suppose you are in step 4 of your example then it should work as follows: Navigate to AStack and execute the subAction which is a reset action which resets AStack and initializes it with the first route.
The problem I was/am facing however is that as soon as the subAction is a reset action and not a navigation action, then it hits the reducer of BStack instead of AStack. When the BStack reducer tries to execute the reset action it throws an error because the route name which was meant for the AStack reducer is not known to the BStack reducer... I think that's a bug but I didn't have time to investigate this further. Did you get this working with an reset action ?

**Comment by vonovak** [comment]
@nico1510 yes, I agree. I tried the same approach and encountered the same problem. I haven't investigated further. I might take another look at this some time later. Please let me know if you find a fix.

**Comment by vonovak** [comment]
@nico1510 by the way, next time you make a PR that you know is buggy, it would be nice to say so and try to make it work right

**Comment by nico1510** [comment]
I investigated further and created a PR which should fix the issue with `replace` not working. Once that is merged I will create another PR with `replace`.
And by the way @vonovak next time you blame people which trying to improve this library consider to spend this time by contributing instead ;)

**Comment by vonovak** [comment]
I didn't mean it personally. It's only that trying to merge a PR, knowing it doesn't work, is just not right. I'd happily contribute, just like I did with ex-navigation, for example, but seeing how slowly the PRs are reviewed, it would be a waste of time.

**Comment by nico1510** [comment]
The change does 'work' in terms of fixing the bug. It just doesn't do a good job in cleaning up the state but this wasn't done before neither. The only difference to before is that one more route is added on top of the stack.

**Pull request merged**
