### PR TITLE
Hide overflow on individual pages in tab view

### PR DESCRIPTION
**Pull request by satya164**
cc @grabbou

### CODE REVIEW

**Comment by santomegonzalo** [comment]
Hi, when this PR will be implemented? is kind of weird that shadow...

**Comment by aimak** [comment]
Is there any news on this ? When will it be deployed ?

**Comment by aimak** [comment]
for the record, it has been deployed as of https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.10

**Comment by eflath** [comment]
I am using beta 10 but this issue is not fixed

**Comment by eflath** [comment]
My setup is as follows:
```
Host StackNavigator
  TabNavigator
    StackNavigator A
    StackNavigator B
    StackNavigator C
    StackNavigator D
```
the TabNavigator is set to lazy=true. When I first launch, the shadow is not present. The shadow appears only on screens whose nearest neighbor to the right has been loaded. If i switch to StackNavigator B (therefore loading that component) then there is a shadow only on StackNavigator A. There is never a shadow on StackNavigator D.

**Pull request merged**
