### PR TITLE
enable `showLabel` prop in `tabBarBottom`

### PR DESCRIPTION
**Pull request by kylpo**
This PR adds the `showLabel` option to tabBarBottom for projects like mine that only want icons visible in the bottom tab bar.

It should be safe, since it is an exact copy/paste from `tabBarTop`. See https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarTop.js#L66

**Test plan (required)**
- All tests passed, though I don't know if any tests have been written to cover `TabBarBottom`

### CODE REVIEW

**Comment by satya164** [comment]
It should probably automatically reduce tabbar height unless specified

**Comment by kylpo** [comment]
Defaults to labels:
defaultlabels

With `showLabel: false`:
showlabelfalse

**Comment by kylpo** [comment]
Thanks for the quick comment @satya164. I personally prefer the height remain unchanged by this prop. I wouldn't want this simple prop to do more than I think it should, which is to just remove the label.

Thoughts?

**Comment by satya164** [comment]
Ok, this looks good enough. I was worried it'll leave blank space below.

**Comment by ericvicenti** [comment]
This LGTM! Thanks @kylpo!

**Pull request merged**
