### PR TITLE
CardStack: Don't overwrite custom transitionConfig with default

### PR DESCRIPTION
**Pull request by lintonye**
- The custom `transitionConfig` in `CardStack` is currently always overridden by `defaultConfig`. This causes `transitionConfig` to be ignored.
- The propType of `CardStack` requires `transitionConfig` to be a function. So, `this.props.transitionConfig` => `this.props.transitionConfig()`

**Test plan (required)**

- Write a custom navigation view which renders to a `CardStack` and test if the transition animation behave as expected:

```jsx
class CrossFadeTransitioner extends Component {
    render() {
        const transitionConfig = {
            screenInterpolator: (sceneProps: NavigationSceneRendererProps) => {
                const { position, scene, progress } = sceneProps;
                const { index } = scene;
                const inputRange = [index - 1, index, index + 1];
                const opacity = position.interpolate({
                    inputRange,
                    outputRange: [0, 1, 0],
                });

                return { opacity };
            }
        }
        return (
            <CardStack mode="card"
                navigation={this.props.navigation}
                router={this.props.router}
                transitionConfig={() => transitionConfig}
                />
        )
    }
}

```

### CODE REVIEW

**Comment by satya164** [comment]
cc @ericvicenti

**Comment by ericvicenti** [comment]
What bug does this fix? I think I've seen a related issue

But the change looks good to me! Is there any documentation that needs to be updated?

**Comment by grabbou** [comment]
Up: @lintonye

**Comment by nihgwu** [comment]
why this is still pending?

**Comment by lintonye** [comment]
@ericvicenti  This PR makes `transitionConfig` in `CardStack` actually work.

I don't think there're any documentation changes needed since `CardStack` itself isn't documented.

**Comment by brennanerbz** [comment]
Let's get this in!

**Comment by kuka** [comment]
Anybody with write access, what’s the hold up?

**Comment by brennanerbz** [comment]
@lintonye once this gets merged, can you include a fully fleshed out example?

**Comment by lintonye** [comment]
@brennanerbz Sure, check out this: https://github.com/lintonye/react-native-diary/blob/master/transitions/app/CrossFadeTransitioner.js

Also this post: http://www.reactnativediary.com/2016/12/22/navigation-experimental-custom-transition-2.html

**Pull request merged**
