### PR TITLE
Use animatable text component for the header title

### PR DESCRIPTION
**Pull request by fdnhkj**
# Motivation
This PR replaces `Text` component by its animatable version `Animated.Text`.
Having an animatable component for the header title allows features like the change of header title opacity based on the scroll animation.

auto-hiding-header

### CODE REVIEW

**Comment by matthamil** [comment]
Is this a necessary change? Can this be achieved by using the library's [headerTitle](https://reactnavigation.org/docs/navigators/stack#headerTitle) navigationOption?

**Comment by fdnhkj** [comment]
To me, it is.
If I would have to implement that feature with `headerTitle` navigationOption, I would keep a copy of react-navigation's `HeaderTitle` component within my app and adapt it with this change.

Instead, I think it is better to do it directly in react-navigation's `HeaderTitle` component.
It is like the Animated present in [`Header`](https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L290) component.

**Comment by fdnhkj** [comment]
@matthamil Please let me know if you have any concern about this change.

**Comment by skevy** [comment]
@fdnhkj this seems fine to me. Can you fix the linting errors? You need to run HeaderTitle through Prettier.

**Comment by fdnhkj** [comment]
@skevy Done :)

**Comment by fabriziogiordano** [comment]
@fdnhkj would you mind pasting an example on how to use this new feature?

**Comment by fdnhkj** [comment]
@fabriziogiordano I didn't have time to test it but this should give an idea.
```
// Within a screen component
static navigationOptions = ({ navigation }) => {
    return {
      title: 'MyScreen',
      headerTitleStyle: {
        opacity: navigation.state.params === undefined
          ? 1
          : navigation.state.params.headerTitleOpacity
      }
    };

componentWillMount() {
    this.animatedValue = Animated.Value(1);
    this.props.navigation.setParams({
      headerTitleOpacity: this.animatedValue
    });
  }

componentDidMount() {
    Animated.startTiming(this.animatedValue, {
        toValue: 0.5,
        duration: 500
    }).start();
}
```

**Pull request merged**
