### PR TITLE
Trivial: Ignore the jest setup file when calculating test coverage.

### PR DESCRIPTION
**Pull request by plasticine**
I’m interested in trying to tighten up the test suite and tooling to try and help support contribution and accessibility of the codebase.

This PR make a few really minor changes around the test suite and coverage collection. Namely it;

- excludes the runner setup file from coverage
- includes the actual library codebase in coverage to get a more realistic picture of coverage

I would love to get this merged as I’m interested in trying to work on some reliability and stability issues and IMO it’s critical for to have a test suite that is maintained.

Naturally this will result in a massive decrease in coverage, but at least that number is a real number and not a false indication of actual coverage.

### Before
screen shot 2017-09-14 at 2 51 25 pm

### After
screen shot 2017-09-15 at 9 43 42 am

### Test plan (required)

1. Run `jest` without this diff and see the jest setup file included in coverage
2. Run `jest` with this diff and don’t see the jest setup file included in coverage and see the actual state of coverage by the test suite over the codebase.

### CODE REVIEW

**Comment by plasticine** [comment]
@spencercarli thanks for master merge 👌

**Comment by spencercarli** [comment]
@plasticine sure thing! Going to merge this PR (and your other) - just waiting on circle right now 😄

**Comment by spencercarli** [comment]
While I wait though I do want to thank you for your effort in this and your other PR! Though it's sad to see all the red it is, as you said, extremely important to the success of this library!

**Comment by plasticine** [comment]
> While I wait though I do want to thank you for your effort in this and your other PR! Though it's sad to see all the red it is, as you said, extremely important to the success of this library!

@spencercarli don’t mention it, both PRs are tiny 😃 Keen to help out if I can.

**Pull request merged**
