### PR TITLE
Fix cardStack style

### LINKED ISSUE #1026: Can't change card background anymore
I think that cardStyle prop for StackNavigator has some problems, since before recent update this code worked:

```
var AppNavigator = StackNavigator({
    ...
}, {
    headerMode: 'screen',
    cardStyle: {
        backgroundColor: 'white'
    }
});
```
and now I don't know how to change the background of all screens to white.
I see that at line 169 of [https://github.com/react-community/react-navigation/blob/master/src/views/CardStackTransitioner.js](url) cardStyle prop isn't passed to CardStack component.

### PR DESCRIPTION
**Pull request by grabbou**
Nit: we pass `style` instead of `cardStyle`.

Fixes #1026

### CODE REVIEW

**Comment by ericvicenti** [comment]
@grabbou, can you make sure this feature is documented properly?

**Comment by migueloller** [comment]
This change breaks styling: https://github.com/react-community/react-navigation/commit/52e24dd38051d75e1b077193d77d668301edaaaa#commitcomment-21759833

**Comment by ugiacoman** [comment]
Think there may be a bug here.

I've tried
```
  Schedule: {
    screen: Schedule,
    navigationOptions: {
      header: null,
      cardStyle: {
        backgroundColor: 'red'
      }
    }
  }
```
and
```
  Schedule: {
    screen: Schedule,
    navigationOptions: {
      header: null,
      style: {
        backgroundColor: 'red'
      }
    }
  }
```

Neither of these solutions are working.

**Comment by felipap** [comment]
Same here, can't get this to work. :/

**Comment by felipap** [comment]
I believe adding the following to `_renderCard()` inside `CardStack.js` fixes it.

```js
_renderCard(...) => ... {
    // ...
    const { cardStyle } = this._getScreenDetails(scene).options; // new
    // ...
    return (
      <Card
        {...this.props}
        key={`card_${scene.key}`}
        style={[style, this.props.cardStyle, cardStyle]} // modified
        scene={scene}
      >
        {this._renderInnerScene(SceneComponent, scene)}
      </Card>
    );
}
```

@ericvicenti should I make a PR?

**Comment by danieldelouya** [comment]
@felipap Thank you!! I spent almost an entire day trying to figure out how to change the color. Can't believe there hasn't been a PR to this yet.

**Pull request merged**
