### PR TITLE
Custom Title component not rendering on Android.

### PR DESCRIPTION
**Pull request by cleverinventor**
If you specify a custom component for options.title it was rendering on iOS but on Android you received an error about not being able to nest a View in side of Text.

Please provide enough information so that others can review your pull request:

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure you test on both platforms if your change affects both platforms.

The code must pass tests and shouldn't add more Flow errors.

**Code formatting**

Look around. Match the style of the rest of the codebase.

### CODE REVIEW

**Comment by vonovak** [comment]
The docs say that "title (is a) String that can be used..." so using a custom component for options.title is not supported.

**Comment by cleverinventor** [comment]
@vonovak  Line 86 originally was "details.options.headerTitle", but there is no headerTitle in options, I believe this was a typo because "option.title" does exist and the next line checks to see if headerTitle is a string. If it is not then it just pass whatever object it is as the component to render.

**Comment by vojtechnovak** [comment]
Check https://reactnavigation.org/docs/navigators/stack, the `headerTitle` option does exist and can be a string or react element. I think the correct as it is.

**Comment by vonovak** [comment]
I tested custom element in header title using `headerTitle` and it works. Hence I'm closing this.

**Pull request closed without merging**
