### PR TITLE
Accept a `tabBarOnPress` param

### PR DESCRIPTION
**Pull request by cooperka**
### Changes

Accept a `tabBarOnPress` param for `TabNavigator` to handle tap events. If provided, this method will be called instead of the default, and the tab will **not** be changed automatically.

The API is consistent across Android and iOS (`TabBarTop` and `TabBarBottom`).

Hopefully resolves https://github.com/react-community/react-navigation/issues/314.

### Usage

```jsx
const MyTabs = TabNavigator({
  ...
}, {
  tabBarComponent: TabBarBottom /* or TabBarTop */,
  tabBarPosition: 'bottom' /* or 'top' */,
  navigationOptions: ({ navigation }) => ({
    tabBarOnPress: (scene, jumpToIndex) => {
      console.log('onPress:', scene.route);
      jumpToIndex(scene.index);
    },
  }),
});
```

### Test Plan

1. Copy the code above into the NavigationPlayground example app
2. Run the app and try it out with both TabBarBottom and TabbarTop

### CODE REVIEW

**Comment by skyworld** [comment]
This is very helpful to me！
非常感谢

**Comment by cooperka** [comment]
@satya164 agreed. I'll try to refactor soon.

**Comment by cooperka** [comment]
@satya164 thanks for the feedback. I've implemented `tabBarOnPress` as a Navigation Option per your suggestion. It does depend on one small change in react-native-tab-bar: https://github.com/react-native-community/react-native-tab-view/pull/231.

I understand you'd eventually like to use event emitters per [your RFC](https://github.com/react-community/react-navigation/issues/1363), but by the looks of things that will probably take some time to spec and implement. I think this PR is a **good workable solution until then** (and may not need to change even after the proposal).

The [older PR](https://github.com/react-community/react-navigation/pull/525) that adds an `onTabPress` callback does not allow for overriding/canceling/ignoring the tap event; this PR does, which is very necessary for several legitimate use cases that have been discussed in past issues.

What are your thoughts on these changes?

**Comment by cooperka** [comment]
*Note to reviewers: I'll be traveling for the next couple weeks. Hopefully this can be merged without issue, but I'll try to respond to comments when possible (or on May 23 when I return). Branch is rebased and up to date, and owners have permission to push directly to this branch:*

```console
git remote add cooperka https://github.com/cribspot/react-navigation.git
git fetch cooperka
git checkout -b tab-bar-on-press
```

**Comment by WillyRamirez** [comment]
Will `tabBarOnPress` receive the navigation prop? I want to open the drawer using a tabbar press and for as far as I know I need the navigation object for this.

**Comment by itswaze** [comment]
jumpToIndex won't work...
alert(scene.index); shows the right index and works, but jumpToIndex won't call the function.

**Comment by cbjs** [comment]
any progress ?

**Comment by gregorykan** [comment]
any update on this, @cooperka @satya164 ?

**Comment by cooperka** [comment]
Just waiting to hear his thoughts; I can rebase and clean up for merge any time if this is the right direction.

Seems like the owners are quite busy right now, so in the meantime @gregorykan you can always fork this repo in order use this feature in your app right away if necessary. I can give you more instructions if you need help doing it, just let me know.

**Comment by mazing** [comment]
+1

**Comment by danielreed07** [comment]
+1

**Comment by dioxide** [comment]
+1

**Comment by danstepanov** [comment]
+1

**Comment by nataroo** [comment]
@cooperka I forked your repo and used tabBarOnPress as a navigation option on my tab navigator and the callback works great.  My app has a redux integration and I need to fire an action to the redux store when the tabBarOnPress is called.  Any idea how I can do that inside the TabNavigator's navigation options?

**Comment by cooperka** [comment]
@nataroo hmm, if you could figure out a way to have `dispatch` in scope within `tabBarOnPress` that would be easy. Otherwise, you could use [screen tracking with redux](https://reactnavigation.org/docs/guides/screen-tracking#Screen-tracking-with-Redux) (this is what I do in my app, and it's very useful). There may be other solutions, too.

**Comment by danstepanov** [comment]
@cooperka Is there ETA on when this might be merged? What is holding this up, exactly?

**Comment by nataroo** [comment]
@cooperka I looked at screen tracking with redux - from what I understand onNavigationStateChange will be called whenever the screen changes.  However in my case, I change the tabs sometimes programmatically but I want to fire the redux event only when the user changes tabs.  I don't think onNavigationStateChange would be able to differentiate between the two.  I am not able to get dispatch in scope within the tabBarOnPress.  tabBarOnPress is in a TabNavigator which is a const.  I am not sure how to connect a const to a redux store.  I tried returning the TabNavigator from a react component's render method, but that doesn't work either.

**Comment by cooperka** [comment]
@danstepanov your guess is as good as mine 😕 it seems like the maintainers are very busy and haven't been merging very many PRs lately. If you need this in your app, you can always fork this repo and do it manually for now.

**Comment by cooperka** [comment]
@nataroo could you simply use the `dispatch` provided, since you're already connected to redux? I haven't tested this, but it might work:

```js
  navigationOptions: ({ navigation }) => ({
    tabBarOnPress: (scene, jumpToIndex) => {
      navigation.dispatch(...);
    },
  }),
```

**Comment by nataroo** [comment]
@cooperka  That doesn't work.  I tried this:

```
navigationOptions: ({ navigation }) => ({
tabBarOnPress: (scene, jumpToIndex) => {
navigation.dispatch(ActionCreators.testMethod(parameter));
},
}),
```

**Comment by fabriziomoscon** [comment]
I forked @cooperka branch and rebased it on top of the latest master:
https://github.com/fabriziomoscon/react-navigation/commits/tab-bar-on-press
I have tested it on iOS and Android and it works on both very well.

I understand this PR might not be in line with the future plans for react-navigation but today it fixes the problem I have! 

Thank you @cooperka 

My implementation is the following:

```javascript
navigationOptions: ({ navigation }) => ({
        tabBarOnPress: (tab, jumpToIndex) => {
            const {
                dispatch,
                state,
            } = navigation
            const stackRouteName = ['FirstScreenTab1', 'FirstScreenTab2', 'FirstSceneTab3'][tab.index]

            // the new tab is not first in the stack
            if (tab.route.index !== 0) {
                // the tab wasn't focused
                if (tab.focused === false) {
                    jumpToIndex(tab.index)
                }
                dispatch(NavigationActions.reset({
                    index: 0,
                    key: state.key,
                    actions: [NavigationActions.navigate({ routeName: stackRouteName })],
                }))
            } else {
                jumpToIndex(tab.index)
            }
        },
```

I hope this could help others stuck with #314

**Comment by cooperka** [comment]
Thanks @fabriziomoscon. I've rebased here again as well.

**Comment by jitinmaher** [comment]
Solved my problem ! Thanks @cooperka !

**Comment by townmulti** [comment]
+1

**Comment by rimzici** [comment]
Need support on this #2239 .

**Comment by IlyaVi** [comment]
+1

**Comment by beausmith** [comment]
# Example: Tapping Tab Always Navigates to Initial Screen of Tab’s StackNavigator

## 1. Install via `package.json`

Install [SHA 187913749f61f27e109af841b5558235032652b7](https://github.com/cribspot/react-navigation/commit/187913749f61f27e109af841b5558235032652b7) from <https://github.com/cribspot/react-navigation/tree/tab-bar-on-press>

```
"react-navigation": "git://github.com/cribspot/react-navigation.git#187913749f61f27e109af841b5558235032652b7",
```

Of course this could change if the code in this PR changes.

## 2. Configure TabNavigator

Create a StackNavigator for each tab and use the following TabNavigatorConfig

```javascript
export const TabScreens = TabNavigator({
  TabOne: {
    screen: TabOneStackNavigator
  },
  TabTwo: {
    screen: TabTwoStackNavigator
  }
}, {
  initialRouteName: 'Track',
  navigationOptions: ({ navigation }) => ({
    tabBarOnPress: (tab, jumpToIndex) => {
      if (tab.focused) { // if tab currently focused tab
        if (tab.route.index !== 0) { // if not on first screen of the StackNavigator in focused tab.
          navigation.dispatch(NavigationActions.reset({
            index: 0,
            actions: [
              NavigationActions.navigate({ routeName: tab.route.routes[0].routeName }) // go to first screen of the StackNavigator
            ]
          }))
        }
      } else {
        jumpToIndex(tab.index) // go to another tab
      }
    }
  })
})

```

_Inspired by and slightly more automated than @fabriziomoscon's example above._

**Comment by fabriziomoscon** [comment]
@cooperka have you already tried to rebase the fork on top of master? There are few fixes

**Comment by Sundin** [comment]
+1

**Comment by albinekb** [comment]
Status on this? Is there anything that I can help you with?

**Comment by cooperka** [comment]
Hi @albinekb, as discussed above, it seems like the maintainers are busy and haven't been merging many PRs lately. We've tried pinging them several times to no avail. If you need this in your app, you can always do it manually for now, e.g.:

```js
"react-navigation": "git://github.com/cribspot/react-navigation.git#1879137"
```

**Comment by albinekb** [comment]
Allright! Just tell me if there's anything i can do to make this move :) If the maintainers want it implemented in another way, I can submit a PR for that. Really love this project and want to help if possible!

Thanks for the tip 👌

**Comment by spencercarli** [comment]
Hey all! Just wanted to say that there are a few new folks (myself included) joined to help get this project moving forward again. We're trying to get the issues under control and get some communication lines going before we start merging PRs. I don't have any ETAs at this point but know that we're trying to get the ball moving again 😄

**Comment by broskoski** [comment]
@cooperka (et al.) thanks for your awesome fork that addresses this need.

Just want to point out a seemingly minor issue but actually makes this solution slightly less attractive as it stands (also want to document this for anyone else who stumbles on this thread). More of an issue with `NavigationActions.reset`, than `tabBarOnPress`, but this case is the only time I could imagine it would come up.

In your proposed solution, if the current index isn't 0 we dispatch a reset action like so:

```javascript
navigation.dispatch(NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: tab.route.routes[0].routeName })
  ]
}))
```
The problem here is that it resets all of the state, including the scroll position on the initial route. For an app experience like Instagrams, you can imagine scrolling down in a feed, going down a little way stacking up screens and then wanting to reset right back to where you were initially. I've been looking around a little bit and can't find a solution for getting back to the initial state without resetting everything. 

In any case, I support this PR 👍

**Comment by brentvatne** [comment]
fyi, it's not necessary to fork to have this functionality:

https://github.com/brentvatne/chain-react-conf/blob/master/navigation/CustomTabBarBottom.js
https://github.com/brentvatne/chain-react-conf/blob/master/navigation/MainTabNavigator.js#L68-L87

**Comment by cooperka** [comment]
@brentvatne I would argue that installing from a minor fork is much easier than copying in a whole custom component just to handle `onPress` :) but thank you for the awesome example!

**Comment by brentvatne** [comment]
to each their own! either way, this type of functionality is pretty important

**Comment by seratonik** [comment]
+1

**Comment by sospedra** [comment]
First of all, I want to make clear that **I strongly support this PR**. Tho I think there's a much simplier and safe (I don't trust forks from betas): override the `TabBarComponent`.

Here's a working example

```js
// CustomTabBar.js
import React from 'react'
import { NavigationActions, TabBarBottom } from 'react-navigation'

const getCurrentTabRoot = (state) => {
  return state.routes[state.index].routes[0].routeName
}

const resetTabNavigation = (dispatch, rootRouteName) => {
  dispatch(NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({
      routeName: rootRouteName,
    })],
  }))
}

export const Lowerbar = (props) => {
  return <TabBarBottom
    {...props}
    jumpToIndex={(index, ...args) => {
      // if trying to move to the same tab
      if (index === props.navigation.state.index) {
        // reset the navigation
        resetTabNavigation(
          props.navigation.dispatch,
          getCurrentTabRoot(props.navigation.state),
        )
      }
     
      // in any case proceed with normal jumpToIndex functionality
      props.jumpToIndex(index, ...args)
    }}
  />
}
```

This small component will be added as `TabNavigatorConfig` option

```js
import CustomTabBar from './CustomTabBar'

TabNavigator({
  MyRoute: {
    screen: MyRoute,
  },
  /* more routes */
}, {
  tabBarComponent: CustomTabBar,
})
```

**Comment by cooperka** [comment]
Thanks for the example @sospedra! Luckily this no longer requires a fork as my other PR was merged a while ago. I've updated this PR description accordingly.

**Comment by fabriziomoscon** [comment]
@sospedra how would you make it work for `TabBarTop`?
@cooperka I am totally confused by your statement. Could you please add more context? Are you talking about this issue? Was a PR merged?

**Comment by cooperka** [comment]
Hi @fabriziomoscon, I'm replying to @sospedra's concern that this PR relies on a forked version of react-native-tab-view (specifically https://github.com/react-native-community/react-native-tab-view/pull/231). This is no longer true, because that PR was merged and included in `v0.0.63` so a fork of react-native-tab-view is no longer necessary.

**Comment by sospedra** [comment]
@fabriziomoscon I didn't tried, but I'm pretty sure that would be same but overriding `TabBarTop` instead of `TabBarBottom`

**Comment by albinekb** [comment]
@spencercarli what's stopping this from being merged? If I create a new PR towards `master`, can you merge it? Do you want anything changed? It's such a small change it feels bad to let everyone wait for it...  💯  I'm happy to help! Thanks.

**Comment by cooperka** [comment]
@albinekb please don't create a duplicate PR, that will just slow things down even more 😊  as repeated above, the team is bogged down right now so things are just moving very slowly.

If you want to use this code right now, feel free to reference my fork directly. It's rebased and up-to-date as of yesterday, but I'm happy to rebase again if needed.

**Comment by albinekb** [comment]
I tried your fork, but got this error

```
Warning: Failed prop type: The prop `onIndexChange` is marked as required in `TabViewAnimated`, but its value is `undefined`.
    in TabViewAnimated (at TabView.js:195)
    in TabView (at withCachedChildNavigation.js:60)
...
```

Seems like the fix is in this PR https://github.com/react-community/react-navigation/pull/2527
It would be awesome if you had time to rebase your fork, otherwise tell me and I'll set up my own and post it here. Thanks @cooperka 🙌

**Comment by cooperka** [comment]
@albinekb done!

**Comment by harbi** [comment]
Thank you @cooperka for your efforts!

I'm using your changes to display a screen as a modal from the tab bar, which is not possible now without workarounds.

untitled

My implementation is as the following:

```javascript
const Tabs = TabNavigator({
  TabOne: {
    screen: TabOneStack,
    // icon and other options
  },
  TabTwo: {
    screen: TabTwoStack,
    navigationOptions: ({ navigation }) => ({
      tabBarOnPress: (tab, jumpToIndex) => {
        navigation.navigate('TabTwoModal');
      },
    }),
  },
  TabThree: {
    screen: TabThreeStack,
    // icon and other options
  },
});


const App = StackNavigator({
  Tabs: {
    screen: Tabs,
  },
  TabTwoModal: {
    screen: TabTwoStack,
  },
}, {
  mode: 'modal',
  headerMode: 'none',
});
```

**Comment by spencercarli** [comment]
🎉 🎉 🎉

**Comment by albinekb** [comment]
Awesomeness, thanks for merging this! ❤️

**Comment by diegorodriguesvieira** [comment]
❤️

**Comment by endtojunc** [comment]
I have tried to put the param but I still not able to get the callback. Can anyone tell me where it went wrong? 

```
Wallet: {
    screen: WalletStack,
    path: 'wallet',
    navigationOptions: ({navigation}) => ({
      tabBarOnPress: (scene, jumpToIndex) => {
        console.log('test', scene.route);
        jumpToIndex(scene.index);
      },
      tabBarLabel: TAB_TEXT.TAB_WALLET,
      tabBarIcon: ({tintColor}) => (<Image
        source={require('../images/icon_wallet.png')}
        style={[
        navStyles.tabar_icon, {
          tintColor: tintColor
        }
      ]}/>)
    })
  },
```

**Comment by rmevans9** [comment]
@endtojunc are you using the version from NPM or are you using the master branch?

**Comment by endtojunc** [comment]
@rmevans9 I'm using the version from NPM. How can I use the master branch? Thanks!

**Comment by rmevans9** [comment]
This has not been released yet so it won't be on NPM. If you want to use the master branch directly you can follow this:

https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by antakov** [comment]
after this it works
npm install git+https://git@github.com/react-community/react-navigation.git

**Comment by cooperka** [comment]
@antakov it's best practice to avoid referring to a dynamic branch like that (it defaults to `master` which changes over time). A better solution would be to include a specific commit hash so it doesn't change unexpectedly:

```bash
npm install git+https://git@github.com/react-community/react-navigation.git#fe4b1e2
```

**Comment by itswaze** [comment]
does anyone know how to implement scroll to top using `tabBarOnPress`?

**Comment by JoseVf** [comment]
@cooperka do I have to have GIT installed to include that specific commit on my project?

**Comment by cooperka** [comment]
Hmm, I have no idea @JoseVf! My best recommendation is to search for that error online. I would guess you probably do need git, since it's installing from a git repo.

**Comment by albinekb** [comment]
Yes @itswaze use `tabBarOnPress` with [<ScrollView> scrollTo](https://facebook.github.io/react-native/docs/scrollview.html#scrollto) If you need more help feel free to join [this slack](https://zeit.chat) and contact me there. I'm @albinekb there too :) Don't want to clutter this issue with chat/support 😄

**Comment by arled** [comment]
`tabBarOnPress` does not call at all for me.

**Comment by bakarshams** [comment]
@cooperka Hi. I really appreciate your contributions. I want to reset the whole stack navigation of my tabs app.
Tabs Nav(Parent Navigator)
Tab 1 (Stack Nav)
Tab 2 (Stack Nav)
Tab 3 (Stack Nav)
I used tab tabBarOnPress to reset stack:

tabBarOnPress: (tab, jumpToIndex) => {
      const {
          dispatch,
          state,
      } = navigation
      if (tab.focused) { 
            dispatch(NavigationActions.reset({
              index: 0,
              actions: [
                NavigationActions.navigate({ routeName:"HomeScreen" })
              ]
          }))
      } else {
        jumpToIndex(tab.index) // go to another tab (the default behavior)
      }
  }

The issue is:
After the reset, it says that "There is no route defined for key HomeScreen" but I can see in console that homescreen component has been executed coz I have put some console statements there.

Please help me regarding this.

**Comment by albinekb** [comment]
I have the same issue @bakarshams, I think it's a bug with `reset`, but I have no solution for it now, I'm working around it with very ugly hacks.

**Comment by JoseVf** [comment]
@cooperka is there any way to set `screen` property nullable/not required? I have in my tabBar a `logout` button that just shows up a modal with an `Accept` and `Cancel`, but I have to create a empty screen (actually just the necesary thing to be referenced as a screen) just to avoid the error (example code below).

```
const tab_bar = TabNavigator({  // This tabNavigator is inside a stackNavigator, wich contains the 'login' view
   Home: {
     screen: Home
   },
   Logout: {
     screen: Logout     // Empty screen, useless in this specific case
       ,navigationOptions: ({navigation}) => ({
           tabBarOnPress: (scene, jumpToIndex) => {
               return Alert.alert(   // Shows up the alert without redirecting anywhere
                   'Confirmation required'
                   ,'Do you really want to logout?'
                   ,[
                     {text: 'Accept', onPress: () => { navigation.dispatch(NavigationActions.navigate({ routeName: 'login' }))}},
                     {text: 'Cancel'}
                    ]
               );
           },
       })
    },
});
```

**Comment by cooperka** [comment]
@JoseVf it sounds like you're looking for custom tab items that don't refer to an actual scene. That's not currently possible without overriding `tabBarComponent` (see docs [here](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig)). If you override that component you can make the tabs do whatever you want.

**Comment by wellyshen** [comment]
@albinekb How to handle ScrollView scrollTo with tabBarOnPress. Can you please give me an example?

**Comment by danstepanov** [comment]
This is now available in prerelease "react-navigation": "^1.0.0-beta.13" :)

**Comment by cooperka** [comment]
Hi @sanjayholla94, that's a strange issue you're facing! I recommend opening a [new issue](https://github.com/react-community/react-navigation/issues) to discuss more easily. Good luck!

**Comment by sanjayholla94** [comment]
Created a new issue for the same: https://github.com/react-community/react-navigation/issues/2725

**Comment by itswaze** [comment]
Does anyone know how to implement both scroll to top and reset stack with `tabBarOnPress`?
Like, the first click scrolls to top and the second one resets the stack.

**Comment by albinekb** [comment]
Yes @itswaze, you need to

- Check what tab you're on
    - If it's the same tab
        - Check if it's focused
            - If it's focused check the scroll position

And add the desired logic for which action to call, hit me up in the slack i linked to you if you wanna chat :) Don't want to have support in this issue 👍

**Comment by marceloHashzen** [comment]
Hello everyone, I'm new to React Native and have been playing with navigation to learn how it works. My problem here is that I have a main tab navigator with three tabs, and the first app have three stack navigators inside, Home, Module 1 and Module 2.
When I enter the app, Home is showed then I have to click for the other modules. So I want to tap the first tab button to navigate back to the Home screen, but resetting the tab stacks, so it is not possible to swipe back using the stack header or the android back button.

My code is the following:

Main tab navigator:

`export const MainTabs = TabNavigator({
    Home: {
        screen: HomeStack,
        navigationOptions: ({ navigation }) => ({
            tabBarIcon: ({ tintColor }) => <Icon name="home" size={22} color={tintColor} />,
            tabBarOnPress: (tab, jumpToIndex) => {
                console.log(tab.focused);
                if (tab.focused) {
                    jumpToIndex(tab.index);
                }
            },
        }),
    },
.......`

The Home stack:

`export const HomeStack = StackNavigator({
    Home: {
        screen: HomeScreen,
    },
    Module1: {
        screen: Module1Stack,
    },
    Module2: {
        screen: Module2Stack,
    },
},
{
    headerMode: 'none',
});`

`jumpToIndex` is not working (I'm using the master branch) so I tried with the following:


- This one works, but creates stacks that can be navigated back with a left to right swap (iOS only) and the android back button:
`Home: {
        screen: HomeStack,
        navigationOptions: ({ navigation }) => ({
            tabBarIcon: ({ tintColor }) => <Icon name="home" size={22} color={tintColor} />,
            tabBarOnPress: (tab, jumpToIndex) => {
                navigation.navigate('Home');
            },
        }),
    },`

On the TabNavigator second parameter I've set `swipeEnabled: false,`, but I can still swipe the stack inside the tab...

The full code is in my repo: `https://github.com/marceloHashzen/navigation`

**Comment by pietro909** [comment]
@beausmith is your solution still valid? For me doesn't work since `tab.focused` is always false.

**Comment by valinaga** [comment]
Hi all,

It's really great to have the tabBarOnPress available! 
However, I'm stuck with an issue. The tab navigator is not my top navigator but a screen in a StackNavigator. Something like this:
```
const AppNavigator = StackNavigator({
    main: { screen: MainScreenNavigator },
    login: { screen: LoginScreen },
    recover: { screen: RecoverScreen },
    register: { screen: RegisterScreen },
    photo: { screen: PhotoScreen },
    intro: { screen: IntroScreen }
});

const MainScreenNavigator = TabNavigator({
    home: { screen: HomeNavigator },
    mywishlist: { screen: MyWishBoxNavigator },
    friends: { screen: FriendsNavigator },
   messages: { screen: MessagesNavigator }, 
   more: { screen: MoreNavigator }
});
```
Unfortunately I was not able to make @beausmith  above code work. The issue was that dispatching the reset action was throwing an error because the route name must be from the previous screen  from MainScreenNavigator, but not from the TabNavigator.

My TabNavigator `navigationOptions` and `tabBarOnPress` looks like this:
```
    navigationOptions: ({ navigation }) => ({
      tabBarOnPress: (scene, jumpToIndex) => {
        const { route, focused, index } = scene;
        if (!focused) {  
          if (route.index > 0) {
            const { routeName, key } = route.routes[0];
            navigation.dispatch(
              NavigationActions.reset({
                index: 0,
                key,
                actions: [
                  NavigationActions.navigate({ routeName }) 
                ]
              })
            );
          } else {
            jumpToIndex(index);
          }
        }
      },
    }
```
Any hints will be highly appreciated.
Thanks in advance!

**Comment by danstepanov** [comment]
@albinekb With react-navigation beta 22 and expo sdk 24, your solution returns a redbox of `jumpToIndex is not a function`. I read the breaking changes for all the recent releases and there was a recent modification to `tabBarOnPress` to make `jumpToIndex` available. Any idea what might be wrong?

**Comment by spencercarli** [comment]
@danstepanov there was a breaking change a few versions ago for tabBarOnPress. @albinekb example would now be

```javascript
class Screen extends React.Component {
  static navigationOptions = (props) => {
    return {
      tabBarOnPress: ({ scene jumpToIndex }) => {
        if (!scene.focused) {
          jumpToIndex(scene.index)
        } else {
          props.navigation.state.params.handleTabBarPress(scene)
        }
      },
    }
  }

  ...
}
```

**Comment by danstepanov** [comment]
@spencercarli I have implemented the following and still get the following red box:

```
static navigationOptions = ({ navigation }) => ({
    tabBarOnPress: (tab, jumpToIndex) => {
      if (!tab.focused) {
        jumpToIndex(tab.index);
      } else {
        navigation.state.params.handleTabBarPress(tab);
      }
    },
});
```

screen shot 2017-12-19 at 6 40 37 pm

**Comment by danstepanov** [comment]
I have updated the code to this and now `params` on `navigation` is `undefined`

```
tabBarOnPress: ({ scene, jumpToIndex }) => {
      if (!scene.focused) {
        jumpToIndex(scene.index);
      } else {
        navigation.state.params.handleTabBarPress(scene);
      }
    },
});
```

**Comment by danstepanov** [comment]
Combining both methods and  using the following `tabBarOnPress`, it works!

```
tabBarOnPress: ({ scene, jumpToIndex }) => {
      if (!scene.focused) {
        jumpToIndex(scene.index);
      } else {
        _scrollView.scrollToIndex({ animated: true, index: 0 });
      }
    },
});
```

**Comment by albinekb** [comment]
Great @danstepanov 💪

**Comment by grsmvg** [comment]
Just what I needed. But it still seems a bit buggy since scene.focused for the second tab returns false even though it is focused and scene.index is 1

**Comment by vlimag** [comment]
All you need to do is set a custom onPress event for the TabBarIcon, as follows:
    
   ```
 import Icon from 'react-native-vector-icons/FontAwesome';
    class YourClass extends Component {
      static navigationOptions = ({ navigation, screenProps }) => ({
    title: YourTitle',
    headerTintColor: '#fff',
    headerStyle: {
       backgroundColor: '#000', 
       height: 70,
       elevation: null
     },
    tabBarIcon: ({ tintColor }) => (
      <Icon name = {"user-o"} color={tintColor} size={20} onPress={()=>navigation.goBack()}/>
      ),
    });
    render(){
        return (
         <View><Text>yourScreen</Text></View>
        );
    }
```

**Comment by adrianboimvaser** [comment]
Is there an ETA for this being released?

**Comment by brentvatne** [comment]
it has been released for a long time https://reactnavigation.org/docs/tab-navigator.html#tabbaronpress

**Comment by Periclessan** [comment]
Hi All, 

My project mainly using react navigation tabnavigator for navigation to screen and could like to change tab to HomeScreen. When I copy captioned code "jumpToIndex" is not define, I can't make change in tab navigation.

My Router is:

Stacknavigation:

Home screen -- StackNavigator
----One screen (Tab) --TabNavigator
----Two screen (Tab) --TabNavigator
Profile screen -- StackNavigator
----Three screen (Tab) --TabNavigator
----Home screen (Tab) --TabNavigator

My Code is:

export const HomeStack = StackNavigator({
    Home: {screen: TabNavigator(
      {
      One: {screen: One},
      Two: { screen: Two},
      },
      {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    }
      )},  
    Profile: {screen: TabNavigator(
      {
      Three: {screen: Three},
      Home: { screen: Home},
      },
      {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    }
      )},
When I click Home screen (Tab) at Profile screen, it go to Home screen. But the Tab dose not change to 'One screen (Tab)' and Two screen (Tab), it still show 'Three (Tab)' and 'Home (Tab)'

I don't know how to write the code.

**Comment by fabriziomoscon** [comment]
Expected behaviour when pressing a tab:
- if the current tab is selected and the initial route is focused => do nothing
- if the current tab is not selected => jump to the new tab
- if the route is not the initial one => pop all stacked routes from the sstack to reach the initial route
(this doesn't take scrolls into considerations)
I am not sure if I will be able to remove this code completely with version 2. Does anybody know?

Using version `1.5.2` I could simplify a lot the code reported in my previous comment.

```JavaScript
navigationOptions: ({navigation}) => ({
        tabBarOnPress: ({scene, jumpToIndex}) => {
            // the new scene is the first in the stack
            if (scene.focused === true && scene.route.index === 0) {
                return
            }
            if (scene.focused === false) {
                jumpToIndex(scene.index)
            }
            if (scene.route.index !== 0) {
                navigation.popToTop()
            }
        },
    })
```

Any comment or correction is greatly appreciated

**Comment by Kodax9** [comment]
why mine doesnt work using any onpress example from everyone ?

the one that works for me is
tabBarComponent: ({ jumpToIndex, ...props }) => (
        <TabBarBottom
            {...props}
            jumpToIndex={(index) => {
                    if(props.navigation.state.index === index) {
                        props.navigation.dispatch(NavigationActions.back());
                    } else {
                        jumpToIndex(index);
                    }
                }
            }
        />
    ),

any hint guys ?

**Comment by brentvatne** [comment]
@Kodax9 - please create a new issue and follow the issue template if you believe you have found a bug

**Pull request merged**
