### PR TITLE
Update Screen-Tracking.md

### PR DESCRIPTION
**Pull request by thurt**
updates names in the onNavigationStateChange example function

### CODE REVIEW

**Comment by grabbou** [comment]
Why such change? The function is called in [`componentDidUpdate`](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L110) meaning it receives `previous` and `current` state (after update), not `current` and `next`.

**Comment by thurt** [comment]
will update

**Comment by nihgwu** [comment]
I just want to send a PR to revise this 😂 , but there is still another issue so a PR is on the way

**Comment by nihgwu** [comment]
there you go #549

**Pull request merged**
