### PR TITLE
Add headerBackTitleStyle option

### PR DESCRIPTION
**Pull request by sonaye**
This simple PR adds support for back button title styling.

**Motivation**
Unifying text styles in apps that use custom fonts.

**Testing**
in `examples/NavigationPlayground/js/SimpleStack.js`:
```diff
MyPhotosScreen.navigationOptions = {
  title: 'Photos',
+ headerBackTitleStyle: { textDecorationLine: 'line-through' },
};
```

### CODE REVIEW

**Comment by sonaye** [comment]
Fixed now, missing type.

**Comment by koenpunt** [comment]
I apparently didn't see this one, but I think [my PR](./1083) is a more aligned with the `headerBackTitle` option.

**Comment by grabbou** [comment]
Going to close that one in favour of #1083. Such a pitty you guys have sent it at the same time 🗡

**Comment by sonaye** [comment]
Oh wow, what a coincidence! we all share a common goal at the end, making a great piece of software even better. Let's work on getting that PR merged.

**Pull request closed without merging**
