### PR TITLE
remove 30px offset workaround for screen’s shadow disappearing

### PR DESCRIPTION
**Pull request by nihgwu**
followed with #1036 , check the comments there for more information

### CODE REVIEW

**Comment by ms88privat** [comment]
Thanks for the good job. Will this also work for vertical views (modal screen?)
See: https://github.com/react-community/react-navigation/issues/1109

**Comment by nihgwu** [comment]
Sure, I have mentioned it in#1036

**Comment by grabbou** [comment]
ping @ericvicenti as you were involved in the original discussion

**Comment by nihgwu** [comment]
@ericvicenti any chance to review this?

**Comment by ericvicenti** [comment]
Ok I've tested this and it looks good

**Pull request merged**
