### PR TITLE
Added drawerPosition prop into DrawerView (left - right)

### LINKED ISSUE #87: Support drawer position, `left` or `right`

### PR DESCRIPTION
**Pull request by ferrannp**
Resolves #87.

I also added an entry to the `.gitignore` regarding IntelliJ.

### CODE REVIEW

**Comment by mkonicek** [comment]
Are apps with a drawer on the right common? I don't remember seeing one.

**Comment by mkonicek** [comment]
Hey @ferrannp, how did you test this doesn't break any existing code using React Navigation?

**Comment by satya164** [comment]
@mkonicek I think it'll be useful for RTL languages.

@ferrannp can you post a screenshot?

**Comment by mkonicek** [comment]
Good point about RTL!

**Comment by ferrannp** [comment]
Here the example working with it:

drawerright

I did not find unit tests for the UI like a test for the drawer. Do you plan to add them in the future? Maybe Jest snapshots?

**Pull request merged**
