### PR TITLE
Implement change request in #653

### PR DESCRIPTION
**Pull request by tuyennguyen266**
This PR is for implementing change request of #653 cause it's pending a few weeks.

In tests, added checking `params` to make sure it correct as mentioned in change request after reviewing.

### CODE REVIEW

**Comment by grabbou** [comment]
Thanks for taking care of that! Let's make sure tests are passing and we are good.

**Comment by grabbou** [comment]
This fixes #186

**Comment by ericvicenti** [comment]
Ok, this looks pretty well tested! Thanks for following up on this!

**Comment by nthtran** [comment]
Thanks @tuyennguyen266 for implementing the changes needed to merge! Sorry I was busy for the past month so couldn't update my PR. Thanks @ericvicenti and @grabbou for releasing this in `v1.0.0-beta.9`.

**Pull request merged**
