### PR TITLE
fix: fixing set params and set options methods on BaseNavigationContainer

### PR DESCRIPTION
**Pull request by alexandre1921**
**Motivation**
The latest update [@react-navigation/core@6.4.11](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fcore%406.4.11) broke react navigation and subsequently expo router

**Test plan**

- Create an app
- Create the router
- Try to setParams on a screen
- Try to setOptions on a screen

The change must pass lint, typescript and tests.

### CODE REVIEW

**Comment by satya164** [comment]
You can't call `setParams` on the navigation ref. Please provide a repro showing the issue if there's a bug.

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/b99d3c3a94d7f4efe7fb0309d7a41654c21406ea

**Comment by alexandre1921** [comment]
Thanks for ignoring the PR and fixing this bug yourself.

**Comment by satya164** [comment]
@alexandre1921 so you're upset that I fixed the issue you were having when there was no repro for me to actually understand the issue to know what's the proper fix? people are really entitled.

**Comment by alexandre1921** [comment]
I was just trying to contribute, but again thank you for fixing the issue.

**Pull request closed without merging**
