### PR TITLE
add jest config for react-navigation in docs (#256)

### PR DESCRIPTION
**Pull request by half-shell**
This pull request concerns issue #236. It adds the jest configuration necessary to make react-navigation pass the basic jest's rendering test.

I wasn't sure where to put it since there is no test-related section in the guides. I decided to put it in the redux integration because I was following it when I noticed the issue.

**Test plan (required)**
No test required since this is for docs.

### CODE REVIEW

**Comment by ferrannp** [comment]
I think it would be nice to have a Test section in the docs rather than having this as part of Redux integration.

**Comment by grabbou** [comment]
+1 for that suggestion, what you think @ericvicenti ?

**Comment by ericvicenti** [comment]
Yeah I think it would be great to have a guide for testing.

Not related to this exact issue but Ideally the testing doc would discuss how you can test your app's navigation logic by writing tests for `AppNavigator.router.getStateForAction`

**Comment by half-shell** [comment]
@satya164 @ferrannp I sure agree. But I don't think I'm qualified enough to get the test guide started. I'll add the issue related snippet if it is needed.
Then again, what about the `Invariant Violation: Native module cannot be null.` discussed [here](https://github.com/react-community/react-navigation/issues/256)?

**Comment by tugorez** [comment]
@half-shell @ferrannp  Hi guys, I managed all this test-concerns (with jest) using this in my package.json 
```javascript
{
   .
   .
   .
  "jest": {                                                                      
    "preset": "react-native",                                                    
    "setupFiles": ["<rootDir>/jest/setup.js"],                                   
    "transformIgnorePatterns": [                                                 
      "node_modules/(?!(jest-)?react-native|react-navigation)"                   
    ]                                                                            
  },
  .
  .
  .                                                                              
}  
```

and this mock in **<rootDir>/jest/setup.js**
```javascript
jest.mock('Linking', () => ({                                                    
  addEventListener: jest.fn(),                                                   
  removeEventListener: jest.fn(),                                                
  openURL: jest.fn(),                                                            
  canOpenURL: jest.fn(),                                                         
  getInitialURL: jest.fn(),                                                      
})); 
```

an this in my .flowconfig (in case you're using flow too)
```
[ignore] 

.
.
.
; react-navigation isn't compatible with the newest flow version, ignore it         
.*/node_modules/react-navigation*
.
.
.                                                     
 
```

**Comment by ericvicenti** [comment]
Lets get this in for now, and break out a testing section of the docs later on

**Pull request merged**
