### PR TITLE
Error when building with haul: ref to pathToRegexp.compile

### PR DESCRIPTION
**Pull request by 0xfurai**
Please provide enough information so that others can review your pull request:

## Motivation
Error in source code that cause problem on react native using haul https://puu.sh/AT1uZ/158623d5a4.png

### CODE REVIEW

**Comment by ericvicenti** [comment]
Erm this is strange.. we're using normal documented behavior of pathToRegexp here.. https://github.com/pillarjs/path-to-regexp

I'm not sure whats going on with haul

cc @satya164

**Comment by satya164** [comment]
cc @thymikee

**Comment by thymikee** [comment]
I think it's a quirk in Babel acutally. And haul's failure indicates correct behavior (imho). Wouldn't a module like that be imported like this?:
```diff
-import pathToRegexp from 'path-to-regexp';
+import * as pathToRegexp from 'path-to-regexp';
```
The documentation uses require, so I'd assume you either do the above or:
```js 
import {compile} from 'path-to-regexp';
compile(...)
```

**Comment by ericvicenti** [comment]
Oh, very strange that it somehow works in metro.

I'm not a fan of `import * ...` because I've seen it go wrong under various environments..

@Piotrovskyi, can you change this PR to import compile with `import {compile} from 'path-to-regexp';` ? Thanks!

**Comment by brentvatne** [comment]
@ericvicenti - look good to you now?

**Comment by rodrigobdz** [comment]
@brentvatne About the changelog entry, now that I think about it… It should be add under the _Unreleased_ section, right?

**Pull request merged**
