### PR TITLE
Add pressColor to StackNavigator header options

### PR DESCRIPTION
**Pull request by jamieparkinson**
This resolves https://github.com/react-community/react-navigation/issues/925, adding the option to change the back button's ripple colour. For example:

screenshot_20170405-124107_01

All tests and flow checks are passing. Test plan:

- Don't set `pressColor` in `navigationOptions.header` on a `StackNavigator`. Everything is the same as before.
- Set `pressColor` to anything you want as above. Ripple colour has changed.

Do let me know if there's anything you'd prefer to be done differently :slightly_smiling_face:

### CODE REVIEW

**Comment by jamieparkinson** [comment]
@ericvicenti Agreed, although worth remembering that this means `pressColor` will be inconsistent between StackNavigator and TabNavigator. Will do this later today.

**Comment by ericvicenti** [comment]
Is `pressColor` on TabNavigator also used on Android only? If so, then maybe we should rename it

**Comment by jamieparkinson** [comment]
Yeah, it is Android only - I copied the explanation of 'my' `pressColor` in the docs from TabNavigator. That said, it's only an option for `TabBarTop`, so I guess some level of Android-specificity is implied already

**Comment by ericvicenti** [comment]
Looks great, thanks for the contribution!

**Comment by jamieparkinson** [comment]
@ericvicenti thanks for the great library!

**Pull request merged**
