### PR TITLE
Update docs on headerLeft/Right

### LINKED ISSUE #1124: [Docs] Inaccurate docs for `navigationOptions`
Docs for `navigationOptions` say

```
**headerRight** 
String or React Element to display on the right side of the header

**headerLeft** 
String or React Element to display on the left side of the header
```

Apparently this is not true - it fails on strings.

react-native: 0.43.3
react-navigation: https://github.com/react-community/react-navigation.git#4c55887

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #1124 - regression after flat options.

CC: @ericvicenti

### CODE REVIEW

**Comment by ericvicenti** [comment]
Maybe we should just actually support strings? That way we can bring the options to parity with Airbnb Native navigation

**Comment by grabbou** [comment]
Not sure what would be the use case for a string in `headerLeft` though. Maybe Airbnb navigation does something different with them? e.g. takes it and makes a button with that label?

I'd be open to discussing it as a feature request - that PR is just to remove confusion :)

**Comment by ericvicenti** [comment]
Ok, merging now to reduce immediate confusion.

**Comment by grabbou** [comment]
Created #1215 to follow up.

**Pull request merged**
