### PR TITLE
add doc for transitionConfig

### LINKED ISSUE #1490: Provide an example of using a custon transitionConfig in StackNavigator
Currently, docs say the following:
    `transitionConfig` - Function to return an object that overrides default screen transitions

However, no example is provided what that function should look like.

### PR DESCRIPTION
**Pull request by nihgwu**
close #1490

### CODE REVIEW

**Comment by matthamil** [comment]
I think a cleaned up version of timrc's answer in https://github.com/react-community/react-navigation/issues/1490#issuecomment-304801223 on the same issue would be a great addition to this in the documentation.

**Comment by nihgwu** [comment]
It is a demo for all the `StackNavigator` options, and I think it's enough comparing with the other demos in the docs

**Comment by matthamil** [comment]
This example will work for now. I think it would be great to eventually have more examples in the documentation. Thank you for taking the time to submit this PR!

**Comment by spencercarli** [comment]
Will you move this example down into the "Examples" section at the end of this file? Below the existing content in "Examples". A good title would be

"Modal StackNavigator with Custom Screen Transitions"

Thanks!

**Pull request merged**
