### PR TITLE
Add accessibility label to header back button

### PR DESCRIPTION
**Pull request by JonFridrik**
Add support for accessibility for header back button. As we support accessibility in our app.

### CODE REVIEW

**Comment by JonFridrik** [comment]
@matthamil Hihi. Sure thing :) What file should I update in the docs? Don't know where to put the documentation for the accessibility.

**Comment by ericvicenti** [comment]
Hey there, could you please demonstrate how this was tested? Does it work on both platforms? Why is the accessibility label needed on the title?

Will the app developer ever want to customize the accessibility labels? Maybe they should be configurable as navigation options?

Also, can you adjust the strings to have Title Capitalization?

**Comment by JonFridrik** [comment]
@ericvicenti @matthamil Thank you very much for reviewing :D I will change the accessibility labels so the user can customize them him self. I was wondering where in the docs should I document this? And the test plan how does that work?

**Comment by ericvicenti** [comment]
Because it is a stackNavigator feature, the info can go in that doc. The name could be `navigationOptions.header.backAccessibilityLabel`

**Comment by NetPumi2** [comment]
Hi ... can you rebase and merge it ??

**Comment by grabbou** [comment]
I am going to close this pull request as it has changes requested for more than a month. If anyone (including original author) is willing to continue working on it, feel free to create a new PR that addresses concerns mentioned during the review process.

We are most likely to accept this PR.

**Pull request closed without merging**
