### PR TITLE
Hide tab from TabBar

### PR DESCRIPTION
**Pull request by PerspectivesLab**
this enables an individual tab to show or hide in the tabbar 
```
const TabBar = TabNavigator( {
    
  Catalogue: { 
		screen: Catalog,
		navigationOptions: {
          tabBarLabel:"Catalog",
          tabBarIcon: ({ tintColor }) => <Image source={require('./img/icon.png')} style={[styles.icon, {tintColor: tintColor}]} />
		}
	},                            
  Library: { 
		screen: Library,
		navigationOptions: {
          tabBarLabel:"Library",
          tabBarIcon: ({ tintColor }) => <Image source={require('./img/icon.png')} style={[styles.icon, {tintColor: tintColor}]} />
		} 
	} 
    
	},{
    key: 'Catalogue',
    initialRouteName: 'Catalogue',    
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    tabBarOptions: {
        hideIndex : [ 1 ], // << == this option hides Library from the tab, but content still persists
        showLabel: true,
        showIcon: true
    },  
})    
```

usefull to have an instance running without lost of state or instance, and also still show its content by navigate

### CODE REVIEW

**Comment by spencercarli** [comment]
A few things in regards to this

1. Working based off of indexes is confusing. I think there could be a better way to implement this. Perhaps it's an option in `navigationOptions` instead?
2. Make sure to make any changes to `TabBarTop` as well
3. Documentation for new features is required.

**Comment by vonovak** [comment]
I'm not sure such feature is worth complicating the API of `TabNavigator`. What exactly is your use case? Does this solve a common problem?

**Comment by PerspectivesLab** [comment]
Hi, actually i was proposing this at first in order to have a hidden view ( no tab ) , but instance will be kept through cycles ( no unmount etc ).
i finally ended by implementing my own logic in stackNavigator to retain instances, so this pull request can be closed.

**Comment by nikasvan** [comment]
This was very helpful. Have no idea why it was closed, I think it should be reopened, it's very useful feature!

**Comment by PerspectivesLab** [comment]
i had to add a custom logic in the redux reducer, on navigation, for it to return a state without the page in the router list, so it doesnt get destroyed

**Comment by nikasvan** [comment]
Found the solution for Android. The thing is that for android react navigation is using [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view). So to make it work what needs to change is in _react-native-tab-view/src/TabBar.js_ on line 449 just after components `return` statement add `this.props.hideIndex.indexOf(i) > -1 ? null : <TouchableItem.......` http://prntscr.com/i45qr8

**Comment by PerspectivesLab** [comment]
if you click on the tab "commits" on the top of this page you can currently see the proposed implementation,

**Comment by suarezluis** [comment]
Check my answer here:

https://stackoverflow.com/questions/52362166/react-navigation-hide-one-tab/57515137#57515137

**Pull request closed without merging**
