### PR TITLE
Stack Navigator actions are now idempotent

### PR DESCRIPTION
**Pull request by matthamil**
**ORIGINAL PR: https://github.com/react-community/react-navigation/pull/1588
Closed and reopened due to buggy first fix :)**

Related issues: #135, #1532

Out of the box, the `StackNavigator` does not allow for idempotent pushes. If a user clicks on a component that fires a `navigation.navigate('OtherScreen')` many times from the current screen, the screen will navigate as many times to the screen as the user clicked. This means that the screen will be stacked upon itself a lot of times, so when the user clicks "Go Back", they will have to navigate back through the entire mess of a stack that they created.

idempotent-pushes

Feel free to help me add tests to this to ensure that this always works. As you can see from my gif, it's working pretty great for me.

### CODE REVIEW

**Comment by nihgwu** [comment]
I still don't think this is the right approach

**Comment by matthamil** [comment]
@nihgwu What are your thoughts on a better or another approach to this problem? I would love to see this functionality land in React Navigation and I'm willing to help out. Thanks in advance for the feedback.

**Comment by nihgwu** [comment]
What if I want to navigate to the same screen with different params, in you approach you should count in params too, but that's still not the right way IMO, see #271 for more discussion on this

**Comment by vonovak** [comment]
I would personally like to see this implemented the same way as ex-navigation does it. see [here](https://github.com/expo/ex-navigation/blob/8e39fa82539416f06b9467cab810ab9a5ff82ae8/src/ExNavigationStack.js#L141). What I like about the solution is how simple and it is (more declarative).

**Comment by matthamil** [comment]
I'm going to put my own PR on hold until there is consensus on how this should be handled within the library. There seem to be workarounds posted in https://github.com/react-community/react-navigation/issues/271. If you are reading this, feel free to chime in with your input on how this should be handled by the library, or your thoughts if it shouldn't be handled by the library and left up to the user.

**Comment by GantMan** [comment]
So 99% of the time, people do not want to load additional screens WHILE a screen is being pushed.
On occasion, they might want to load several at a time without waiting for animation to finish.

I suggest we do a flag at the stack level which will allow us to modify the behavior, with the default being off.  No debounce, just hold back any navigation during animation (however long an animation takes).

Should be clean and simple.  Thoughts?

**Comment by stereodenis** [comment]
@matthamil will you reopen this PR?

**Comment by matthamil** [comment]
@stereodenis there is more discussion on https://github.com/react-community/react-navigation/pull/2578 on how to handle idempotent navigation actions. This was accidentally merged because I was trying to update a forked repo with the GitHub GUI. Commit was reverted in https://github.com/react-community/react-navigation/pull/2626

**Pull request merged**
