### PR TITLE
Add `allowFontScaling` option for TabView and `headerTitleAllowFontSc…

### PR DESCRIPTION
**Pull request by finian**
Add `allowFontScaling` option for TabView and `headerTitleAllowFontScaling` for HeaderTitle (#2377)

### CODE REVIEW

**Comment by kelset** [comment]
This looks awesome! Thanks for submitting :)

Can I only ask you one thing? Could you add this new option to the docs too?

**Comment by finian** [comment]
@kelset Sure. I'll update this PR later

**Comment by finian** [comment]
@kelset Docs added

**Comment by kelset** [comment]
THanks @finian - CircleCI is currently having some issues with flowtypes, I'll need to have somebody else help me out to understand why it's failing (doesn't seem related to your code).

**Comment by exKAZUu** [comment]
@kelset @finian The errors are due to these changes. We can remove the errors by adding type information like https://github.com/react-community/react-navigation/commit/6c383e0e8400b385fde4111f3d59e5c8864b02e2

**Comment by kelset** [comment]
Thanks @exKAZUu for the insight, @finian ping me once you update the PR and I'll merge it ;)

**Comment by finian** [comment]
@kelset PR updated

**Pull request merged**
