### PR TITLE
Workaround nested TabNavigation swipe issue

### PR DESCRIPTION
**Pull request by ssssssssssss**
Please provide enough information so that others can review your pull request:

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Workaround nesting TabNavigation swipe bug for Android. 
https://github.com/react-native-community/react-native-tab-view/issues/297

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure you test on both platforms if your change affects both platforms.

The code must pass tests and shouldn't add more Flow errors.

**Code formatting**

Look around. Match the style of the rest of the codebase.

### CODE REVIEW

**Comment by kelset** [comment]
Looks like CI is failing because of Flow issues:

```js
> react-navigation@1.0.0-beta.15 flow-check /root/react-navigation
> flow check --show-all-errors

[2017-10-21 18:28:42] File /root/react-navigation/node_modules/art/parsers/svg/text.js is malformed
Error: src/views/TabView/TabView.js:205
205:       props.initialLayout = { width: 1, height: 0 };
                 ^^^^^^^^^^^^^ property `initialLayout`. Property not found in
205:       props.initialLayout = { width: 1, height: 0 };
           ^^^^^ object literal


Found 1 error
npm info lifecycle react-navigation@1.0.0-beta.15~flow-check: Failed to exec flow-check script
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-navigation@1.0.0-beta.15 flow-check: `flow check --show-all-errors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-navigation@1.0.0-beta.15 flow-check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-21T18_28_52_596Z-debug.log
error Command failed with exit code 2.
Exited with code 1
```

I think it should be easily fixable by addding flow types, this comment [should help you out](https://github.com/react-community/react-navigation/pull/2721#issuecomment-336137444).

**Comment by ssssssssssss** [comment]
@kelset Addressed flow issues.

**Comment by vonovak** [comment]
I'm not liking this PR very much - the problems I see are following:

1  we're mutating the props, which is not a good practice, see [the docs](https://reactjs.org/docs/components-and-props.html#props-are-read-only)
2  what if somebody is passing their custom `initialLayout` and they're running on android? We just replace their custom layout with `{ width: 1, height: 0 }`, no questions asked.(!) 
3 @ssssssssssss why is the initial layout specified only for android? The [issue you are mentioning](https://github.com/react-native-community/react-native-tab-view/issues/297) talks about iOS only.

**Comment by kelset** [comment]
I see your points @vonovak, I guess we can revert if you prefer.

That said, here's why it was done [for Android](https://github.com/react-native-community/react-native-tab-view/issues/312) (I guess) and probably based on [this too](https://github.com/Minishlink/react-navigation/commit/c326c9ba43e101d85b8e590ba9fba9ee0652d5c9).

Again, no probs in reverting and changing for a better PR.

**Comment by Minishlink** [comment]
@vonovak @kelset #2843 might help?

**Comment by ssssssssssss** [comment]
@vonovak It's an Android only issue.
@Minishlink 's approach should be more elegant.
Thanks for all your insights.

**Comment by vonovak** [comment]
this was fixed with another PR

**Pull request merged**
