### PR TITLE
Fix actually remove openURL event listener

### PR DESCRIPTION
**Pull request by joeybaker**
Previously, we were creating an anonymous function as the event listener handler. This means we can't un-listen because we don't have a reference to the handler.

### CODE REVIEW

**Comment by vonovak** [comment]
@matthamil can we get this merged?

ad additional description: the important part that got removed is:

```
Linking.addEventListener('url', ({ url }: { url: string }) => {
    this._handleOpenURL(url);
});
```
^ the function passed to `addEventListener` is anonymous.
however, `Linking.removeEventListener('url', this._handleOpenURL);` is called [here](https://github.com/joeybaker/react-navigation/blob/master/src/createNavigationContainer.js#L168) which of course doesn't work, because `this._handleOpenURL` never got registered in the first place!

**Comment by vonovak** [comment]
@spencercarli in an effort to decrease the number of open PRs, I'd like to draw attention to the fact that this PR can be merged

**Comment by vonovak** [comment]
@charpeni I remeber reading somewhere that you have push access to this repo. Can you please take a look at this? thanks

**Comment by spencercarli** [comment]
Thanks @joeybaker!

**Pull request merged**
